---
baseURL: https://bootcamp.prototype.com.my
title: Bootcamp
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/pipelinenetwork/Bootcamp
  geekdocEditPath: content

  geekdocDateFormat: "2 Jan 2006"
  geekdocSearch: true
